### ISSUE TITLE
[🐛BUG]好像所有的频道都失效了，难得有一个可以用的台，都很卡，不能用了，这是什么情况？

### ISSUE THREAD

**Issue by mwh880** [HerbertHe/iptv-sources#101]
好像所有的频道都失效了，难得有一个可以用的台，都很卡，不能用了，这是什么情况？

**Comment by Tangzhch11** [comment]
我以为是我的网络问题呢 原来都没有台了...作者不更新了吗

**Comment by HerbertHe** [comment]
GitHub 构建的问题，可以先用镜像站，暂时没时间改

**Comment by milimilimm** [comment]
等待更新

**Comment by mwh880** [comment]
和镜像站应该没有关系，我看了他们的直播地址，都是一样的，现在时有频道，但是无法播放，要不就是提示地址有问题，要不就是转圈圈，我看了几个源频道地址，都是一样的，应该是源频道地址失效了，但是没有更新

**Comment by leiyou-li** [comment]
我也想学习一下&nbsp; &nbsp;但是部署失败




942118184
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HerbertHe/iptv-sources"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月11日(星期一) 下午2:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [HerbertHe/iptv-sources] [🐛BUG]好像所有的频道都失效了，难得有一个可以用的台，都很卡，不能用了，这是什么情况？ (Issue #101)





 
和镜像站应该没有关系，我看了他们的直播地址，都是一样的，现在时有频道，但是无法播放，要不就是提示地址有问题，要不就是转圈圈，我看了几个源频道地址，都是一样的，应该是源频道地址失效了，但是没有更新

**Comment by mwh880** [comment]
我没有搭建，直接用的站里的源地址，和镜像的源地址，不过现在都是失效的，希望快点修复

**Comment by HerbertHe** [comment]
> 我没有搭建，直接用的站里的源地址，和镜像的源地址，不过现在都是失效的，希望快点修复

那是上游失效了
