### ISSUE TITLE
能否增加新的地资源并支持列表定制[✨Feat]

### ISSUE THREAD

**Issue by Cnmajun** [HerbertHe/iptv-sources#11]
1、希望能增加 https://www.stream-link.org/的列表。
2、多个来源以后，列表实在太长了。可否支持一种客户定制？从列表中选出自己喜欢的频道，然后再生成自己的列表。

**Comment by HerbertHe** [comment]
- 目前不做proxy，你的链接需要地域ip
- 你这个自定义的需求 https://github.com/HerbertHe/iptv-sources-local-checker 这个项目规划中，关注项目查看 README
