### ISSUE TITLE
[🧑‍🤝‍🧑Join]镜像站

### ISSUE THREAD

**Issue by GrandDuke1106** [HerbertHe/iptv-sources#16]
**完善下面的信息 Complete the information**

| 服务商 IDC | Http 协议(Protocol) | 源地址 URL | 自动更新频率 Auto-update frequence |
| --- | --- | --- | --- |
| 腾讯云 | https | <https://iptv.b2og.com> |  2h |

- [x] 同意每两个小时被检测可用性 Confirm to check usability per 2h

**Comment by HerbertHe** [comment]
@GrandDuke1106 感谢您的加入，将在之后的代码更新中自动添加，完成之后关闭 issue
