### ISSUE TITLE
[🐛BUG]启动容器自动退出。

### ISSUE THREAD

**Issue by songhc8** [HerbertHe/iptv-sources#17]
**描述问题 Describe the bug**

启动容器自动退出，退出前attach发现上述故障信息
song@song:~/Documents/iptv-sources$ docker attach caf3
error An unexpected error occurred: "https://registry.npmmirror.com/@rollup/wasm-node/-/wasm-node-4.9.0.tgz: getaddrinfo EAI_AGAIN registry.npmmirror.com".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error https://registry.npmmirror.com/fsevents/-/fsevents-2.3.3.tgz: getaddrinfo EAI_AGAIN registry.npmmirror.com

**如何复现 To Reproduce**
按照提供的脚本运行docker container 自动退出。

**期待结果 Expected behavior**

**截图 Screenshots**

**其他补充 Additional context**

**Comment by HerbertHe** [comment]
提供一下完整的 yarn error 日志，看这个情况是下载包有问题，倒不是项目的问题

**Comment by HerbertHe** [comment]
你重启一下镜像应该就好了

**Comment by HerbertHe** [comment]
淘宝的npm镜像站抖了

**Comment by songhc8** [comment]
谢谢。确实。重新下载镜像就好了

**Comment by HerbertHe** [comment]
镜像没问题，哈哈哈下载包要看淘宝源的情况
