### ISSUE TITLE
[🐛BUG]YanG_1989 Gather频道清单，生成后成加密了。

### ISSUE THREAD

**Issue by cjh19831115** [HerbertHe/iptv-sources#18]
作者解释，只需在分类后面加英文下划线+密码即可“_123456”，如下：
加密节目_123456,#genre#
10003,
所以建议把YanG_1989 Gather改成YanG-1989 Gather

**Comment by HerbertHe** [comment]
等待下个版本修复

**Comment by HerbertHe** [comment]
已修复
