### ISSUE TITLE
请问能否支持Armv7的CPU

### ISSUE THREAD

**Issue by ErDongChen1973** [HerbertHe/iptv-sources#2]
如题

**Comment by HerbertHe** [comment]
测试了一下不支持，MacBook Air M1 构建等待时间很长。卡在了 yarn install 上，构建不成功。

**Comment by HerbertHe** [comment]
现在基本是arm都是64位的了吧emmm

**Comment by HerbertHe** [comment]
https://github.com/HerbertHe/iptv-sources/commit/15a72444a41f9b688a5fcabd527bf68b6e74b2f9 已支持
