### ISSUE TITLE
[✨Feat]能不能加上代理更新节目清单

### ISSUE THREAD

**Issue by cjh19831115** [HerbertHe/iptv-sources#22]
能否在更新清单的时候，使用代理，很多清单更新的时候，都提示update failed 因为github被墙了

**Comment by HerbertHe** [comment]
没太明白你的需求，请给出具体的实例，如果是GitHub网络的问题的话，目前不考虑代理的问题，因为两个小时更新一次，如果走镜像站会有缓存
