### ISSUE TITLE
[🧑‍🤝‍🧑Join] 镜像站

### ISSUE THREAD

**Issue by Eternal-Future** [HerbertHe/iptv-sources#23]
**完善下面的信息 Complete the information**

| 服务商 IDC | Http 协议(Protocol) | 源地址 URL | 自动更新频率 Auto-update frequence |
| --- | --- | --- | --- |
| CloudFlare | https | https://m3u.002397.xyz | 2h |

- [x] 同意每两个小时被检测可用性 Confirm to check usability per 2h

**额外注明：服务商写的CloudFlare 因为该站点是家里云搭建，并使用了CloudFlare Tunnel 由于家里云似乎并不属于IDC 所以填写了CloudFlare 此处可以由您更改

**Comment by HerbertHe** [comment]
等待测试
