### ISSUE TITLE
[🧑‍🤝‍🧑Join] 镜像站

### ISSUE THREAD

**Issue by Eternal-Future** [HerbertHe/iptv-sources#24]
**完善下面的信息 Complete the information**

| 服务商 IDC | Http 协议(Protocol) | 源地址 URL | 自动更新频率 Auto-update frequence |
| --- | --- | --- | --- |
| Koyeb | https | https://iptv-1145141919.koyeb.app/ | None |

- [x] 同意每两个小时被检测可用性 Confirm to check usability per 2h

**额外注明：使用koyeb搭建，不会对最新更新做出保证

**Comment by HerbertHe** [comment]
等待测试

**Comment by HerbertHe** [comment]
@Eternal-Future 这个没有自动更新吗？？

**Comment by Eternal-Future** [comment]
现在可以重新测试看看有没有自动更新
创建了一个自动任务让koyeb每两个小时重启容器一次

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by HerbertHe** [comment]
可以看看文档，不必要自动重启容器也可以自动更新

**Comment by Eternal-Future** [comment]
Koyeb会每过一段时间自动重启容器，到时候创建的自动任务也会失效来着 koyeb是个PaaS平台

我只能想到挂个自动任务通过api来定时重启容器来更新了

😂

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by HerbertHe** [comment]
这个我暂时还不列到镜像站里去，要进一步做可用测试

**Comment by Eternal-Future** [comment]
嗯 好的

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by HerbertHe** [comment]
暂时先关掉了，看修复情况进行reopen
