### ISSUE TITLE
docker镜像无法正常运行[🐛BUG]

### ISSUE THREAD

**Issue by blue-ice-layer** [HerbertHe/iptv-sources#27]
**描述问题 Describe the bug**
yarn install v1.22.19
[1/5] Resolving packages...
[2/5] Fetching packages...
(node:8) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info There appears to be trouble with your network connection. Retrying...

**Comment by HerbertHe** [comment]
网络问题，重新拉就行了
