### ISSUE TITLE
[🧑‍🤝‍🧑Join]

### ISSUE THREAD

**Issue by x-xx-xxx-xxxx** [HerbertHe/iptv-sources#28]
**完善下面的信息 Complete the information**

| 服务商 IDC | Http 协议(Protocol) | 源地址 URL | 自动更新频率 Auto-update frequence |
| --- | --- | --- | --- |
| 家里云 | https |m3u.hackserver.net| 2h |

- [x] 同意每两个小时被检测可用性 Confirm to check usability per 2h

**Comment by HerbertHe** [comment]
@x-xx-xxx-xxxx emmm需要进行可用性的检测，云服务没有上代理吗？

**Comment by HerbertHe** [comment]
建议还是挡一下，不然被d比较不稳

**Comment by HerbertHe** [comment]
测了一下好像不可用啊

**Comment by x-xx-xxx-xxxx** [comment]
稍等...正在忙其他事

**Comment by x-xx-xxx-xxxx** [comment]
**完善下面的信息 Complete the information**

| 服务商 IDC | Http 协议(Protocol) | 源地址 URL | 自动更新频率 Auto-update frequence |
| --- | --- | --- | --- |
| cloudflare | https |https://m3u.hackserver.net | 2h |

- [x] 同意每两个小时被检测可用性 Confirm to check usability per 2h

**Comment by muyueyuan** [comment]
全部都显示无法播放，potplayer提示服务器关闭或地址错误

**Comment by HerbertHe** [comment]
检测不可用

**Comment by x-xx-xxx-xxxx** [comment]
你检测的时候不会正好碰上2小时更新吧,我这几天一直都在关注这一块,访问没有问题啊

**Comment by HerbertHe** [comment]
@x-xx-xxx-xxxx 更新的时候并不会，打断检测的
