### ISSUE TITLE
[🌟Feat]  fanmingming的源 txt源分类丢失

### ISSUE THREAD

**Issue by ouyanglong721** [HerbertHe/iptv-sources#29]
**描述问题 Describe the bug**

m3u源是包含分类信息的，想问下为何txt源丢失了分类信息，使用fanmingming的转换工具转换的m3u是保留了分类信息的

https://fanmingming.com/txt?url=https://live.fanmingming.com/tv/m3u/ipv6.m3u

**如何复现 To Reproduce**
Steps to reproduce the behavior.

**期待结果 Expected behavior**

**截图 Screenshots**

**其他补充 Additional context**

**Comment by HerbertHe** [comment]
因为分类逻辑不一样，并不是 bug，因为项目生成txt是根据来源进行的，而非实际的源信息

**Comment by ouyanglong721** [comment]
> 因为分类逻辑不一样，并不是 bug，因为项目生成txt是根据来源进行的，而非实际的源信息

好的，感谢分享维护，这样的话只能将此项目做备用方案了，目前还是自己用crontab去定时请求更新fanmingming的m3u源及txt源。

**Comment by HerbertHe** [comment]
等待下个版本就支持这个了

**Comment by HerbertHe** [comment]
正在做调试更新

**Comment by HerbertHe** [comment]
@ouyanglong721 已经支持了

**Comment by ouyanglong721** [comment]
> @ouyanglong721 已经支持了

已更新~感谢~
