### ISSUE TITLE
大佬，请问我在openwrt上部署docker后，为何定时sh脚本会报错？

### ISSUE THREAD

**Issue by KNedwin** [HerbertHe/iptv-sources#3]
![image](https://github.com/HerbertHe/iptv-sources/assets/60510597/cbf00cbe-1363-477d-8324-daef4c981d04)
计划任务是设置好的。

![image](https://github.com/HerbertHe/iptv-sources/assets/60510597/7e255958-e0ac-439a-a746-1badd127e253)
![image](https://github.com/HerbertHe/iptv-sources/assets/60510597/20292880-3b31-439d-9e31-0a86a32c2e54)
手动执行脚本或自动执行脚本后会出现如上的新镜像，容器那边就直接报错了。

![image](https://github.com/HerbertHe/iptv-sources/assets/60510597/5784684e-8caf-4455-9272-340fc1579906)
直接执行脚本是这个报错。看报错好像是容器名称被占用？

**Comment by HerbertHe** [comment]
https://github.com/HerbertHe/iptv-sources/commit/1ef61c8ff1de58ba2a428a6c6ab5876e086be83b 这个 commit 里面已经修复了，下载最新的即可～

**Comment by HerbertHe** [comment]
因为下拉的时候没有删掉容器服务导致了，本地容器占用了。脚本里面先删掉了容器，就能解决这个问题了。

**Comment by KNedwin** [comment]
好的，谢谢大佬的开发。

**Comment by KNedwin** [comment]
![image](https://github.com/HerbertHe/iptv-sources/assets/60510597/f8635191-2b3f-45b8-af2e-268a6cf6c24d)
这个老镜像是不是，可以也在脚本里自动删除啊。
我看似乎每次只要跟新，都会多一个新的镜像。

**Comment by HerbertHe** [comment]
是的，不敢动用户本地环境哈哈哈

**Comment by HerbertHe** [comment]
https://github.com/HerbertHe/iptv-sources/commit/d2fb4c05f160bc846ddb689825f447ba3b00a4ea @KNedwin 以及支持删除 dangling images 了，更新脚本文件
