### ISSUE TITLE
[🧑‍🤝‍🧑Join]

### ISSUE THREAD

**Issue by Eternal-Future** [HerbertHe/iptv-sources#33]
**完善下面的信息 Complete the information**

| 服务商 IDC | Http 协议(Protocol) | 源地址 URL | 自动更新频率 Auto-update frequence |
| --- | --- | --- | --- |
| Amazon | https | https://iptv.002397.xyz/ | 2h |

- [x] 同意每两个小时被检测可用性 Confirm to check usability per 2h
- [x] 已经配置 docker 上游镜像同步 Sync docker image from dockerhub
- [x] 源镜像站加入回滚计划 Join Rollback plan

仍然是每两个小时重新部署docker镜像，应该做到了同步 至于回滚计划...暂未了解

**Comment by HerbertHe** [comment]
@Eternal-Future 回滚计划可以看看我最新的视频，就是做上游全挂的兜底

**Comment by HerbertHe** [comment]
你是又换了台服务器部署的嘛？

**Comment by Eternal-Future** [comment]
这次这台是亚马逊免费12个月的服务器来着


________________________________
发件人: Herbert He ***@***.***>
发送时间: 星期四, 一月 11, 2024 4:52:01 下午
收件人: HerbertHe/iptv-sources ***@***.***>
抄送: Eternal-Future ***@***.***>; Mention ***@***.***>
主题: Re: [HerbertHe/iptv-sources] [🧑‍🤝‍🧑Join] (Issue #33)


你是又换了台服务器部署的嘛？

**Comment by HerbertHe** [comment]
哦哦这样啊，确定加入吗？
