### ISSUE TITLE
只能更新部分内容

### ISSUE THREAD

**Issue by PQ0000** [HerbertHe/iptv-sources#34]
**描述问题 Describe the bug**
只能更新部分内容

**如何复现 To Reproduce**
每次启动，试图手动运行更新脚本也是无济于事。

**期待结果 Expected behavior**
能够正常更新使用

**截图 Screenshots**
![屏幕截图 2024-01-11 215843](https://github.com/HerbertHe/iptv-sources/assets/95015222/0ac7e157-bb4c-4bfb-a068-df1b57a8a926)

![屏幕截图 2024-01-11 222402](https://github.com/HerbertHe/iptv-sources/assets/95015222/df9be18c-bcd7-4164-8234-5da716771a30)

**其他补充 Additional context**
yarn install v1.22.19
[1/5] Resolving packages...
[2/5] Fetching packages...
(node:8) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[3/5] Linking dependencies...
[4/5] Building fresh packages...
[5/5] Cleaning modules...
Done in 7.58s.
yarn run v1.22.19
$ tsup
CLI Building entry: src/index.ts, src/serve.ts, src/matrix.ts
CLI tsup v8.0.1
CLI Using tsup config: /app/tsup.config.ts
CLI Target: node16
CLI Cleaning output folder
ESM Build start
ESM dist/index.js          10.65 KB
ESM dist/serve.js          2.20 KB
ESM dist/matrix.js         928.00 B
ESM dist/chunk-YFI6VH5U.js 862.00 B
ESM ⚡️ Build success in 14ms
Done in 0.45s.
yarn run v1.22.19
$ node ./dist/index.js
Fetch m3u from epg.pw China National finished, cost 153.7847678 ms
Fetch m3u from epg.pw China Country finished, cost 208.3743368 ms
Fetch m3u from epg.pw China Province finished, cost 220.7708061 ms
Fetch m3u from epg.pw China finished, cost 231.9299819 ms
Fetch m3u from epg.pw All finished, cost 301.8047196 ms
Fetch EPG from 51zmt.top cc finished, cost 48.3405237 ms
Fetch EPG from 51zmt.top finished, cost 63.0816748 ms
Fetch EPG from 51zmt.top difang finished, cost 65.1232658 ms
Done in 4.01s.
yarn run v1.22.19
$ node ./dist/serve.js
Serving at http://127.0.0.1:8080
If the network supports ipv6, visit http://[::1]:8080

貌似我本地是打不开  https://mirror.ghproxy.com/这个网站的

**Comment by PQ0000** [comment]
我在想是不是因为启用了国内缓存加速的原因？可否选择开启或关闭？

**Comment by HerbertHe** [comment]
@PQ0000 是国内镜像的问题，考虑进行支持环境变量的方式修复

**Comment by HerbertHe** [comment]
https://github.com/HerbertHe/iptv-sources?tab=readme-ov-file#supported-environment-variables

拉最新的镜像

**Comment by HerbertHe** [comment]
已经进行更新操作
