### ISSUE TITLE
无法播放，是否需要iptv6环境？

### ISSUE THREAD

**Issue by phantasy36** [HerbertHe/iptv-sources#4]
您好，我已经部署成功。3000端口打开也能看到相应的m3u文件列表，但是在potplayer中无法打开。播放没有反应。我的网络环境是iptv4，运营商没有给iptv6。是否需要iptv6才能播放？

**Comment by HerbertHe** [comment]
应该是你运营商的问题，也可能是软件的问题，因为没有你的实际测试环境我无法回答。
