### ISSUE TITLE
[🐛BUG]IPTV_CHECKER_URL 应该填什么

### ISSUE THREAD

**Issue by wsgehaishan520** [HerbertHe/iptv-sources#45]
**描述问题 Describe the bug**
我是docker安装，桥接模式，3000访问端口，IPTV_CHECKER_URL 我应该写 127.0.0.1:8080 还是8081 ,不管怎么测试都是返回404
**如何复现 To Reproduce**
Steps to reproduce the behavior.
http://[192.168.2.149:3000/list/o_s_cn_cctv.list](http://192.168.2.149:3000/check/o_s_cn_cctv)
**期待结果 Expected behavior**

**截图 Screenshots**
<img width="1228" alt="image" src="https://github.com/HerbertHe/iptv-sources/assets/45267428/b3c0a4fe-540e-4093-b473-ab707d78bda5">

**其他补充 Additional context**

**Comment by HerbertHe** [comment]
你的 iptv-checker 启动的端口是多少？

**Comment by HerbertHe** [comment]
如果默认的话是 8081，ipv4 是 https://127.0.0.1:8081，如果docker 开启了 ipv6，是 http://[::1]:8081

**Comment by HerbertHe** [comment]
https://github.com/HerbertHe/iptv-sources/discussions/40

**Comment by wsgehaishan520** [comment]
我用8080能正常打开check页面，8081是forbidden

**Comment by HerbertHe** [comment]
那就是你 iptv-checker 的部署问题了，去看一下 iptv-checker 的文档
