### ISSUE TITLE
为什么不把所有的直播源整合成一个呢？

### ISSUE THREAD

**Issue by li5bo5** [HerbertHe/iptv-sources#5]
tivimate很好用，唯一的问题就是不能自动换源。
大佬可以把所有其他人的全部整合在一起。
毕竟各个接口他们重复的太多了。。

一个IPV4，一个IPV6，
一个支持回放，个不支持回放
这样用起来就会方便很多

**Comment by HerbertHe** [comment]
你的需求这不是这个项目的计划，关注这个项目 https://github.com/HerbertHe/iptv-sources-local-checker
