### ISSUE TITLE
[🐛BUG]服务器已关闭或地址错误

### ISSUE THREAD

**Issue by BasinChen** [HerbertHe/iptv-sources#50]
**描述问题 Describe the bug**

**如何复现 To Reproduce**
Steps to reproduce the behavior.

**期待结果 Expected behavior**

**截图 Screenshots**
<img width="377" alt="image" src="https://github.com/HerbertHe/iptv-sources/assets/47102847/f71c6339-0054-4021-b682-f9d0c5299973">

**其他补充 Additional context**

**Comment by HerbertHe** [comment]
源失效，不属于 bug
