### ISSUE TITLE
[🐛BUG] cname可以是github.io吗？部署后列表没有出来

### ISSUE THREAD

**Issue by Guovin** [HerbertHe/iptv-sources#54]
**描述问题 Describe the bug**
cname配置为github.io域名部署后页面中的直播源列表没有出来

**如何复现 To Reproduce**
Steps to reproduce the behavior.

**期待结果 Expected behavior**

**截图 Screenshots**

**其他补充 Additional context**

**Comment by HerbertHe** [comment]
github.io 直接删掉这个选项就行了，github.io 的机制是 https://xxx.github.io/项目名称

**Comment by HerbertHe** [comment]
github.io 默认的解析规则是你的 xxx.github.io 这个仓库

**Comment by HerbertHe** [comment]
你要打开你的 GitHub pages，仓库的 settings 下面从分支部署就行了

**Comment by HerbertHe** [comment]
![Uploading image.png…]()

**Comment by HerbertHe** [comment]
<img width="952" alt="image" src="https://github.com/HerbertHe/iptv-sources/assets/30955264/06a2287e-133a-4bde-b1a5-394a8ceb3afe">

**Comment by Guovin** [comment]
> <img alt="image" width="952" src="https://private-user-images.githubusercontent.com/30955264/303221206-06a2287e-133a-4bde-b1a5-394a8ceb3afe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNzAzMzAsIm5iZiI6MTcwNzM3MDAzMCwicGF0aCI6Ii8zMDk1NTI2NC8zMDMyMjEyMDYtMDZhMjI4N2UtMTMzYS00YmRlLWIxYTUtMzk0YThjZWIzYWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDA1MjcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiY2FiYmRmMTcwZDYzM2Y2NWI1ODU1NmQyMTAzMWZkYzI1YTIzYjA4YzY2ZGIwYTQzMjZjMWRjNTc0OTg1MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t42UQEVqJYatt8jnF7JA4_wS8WsxbMVwrTFXBuguHyQ">

好了，感谢！
