### ISSUE TITLE
都是国人用 readme就不要写英文了[🐛BUG]

### ISSUE THREAD

**Issue by six00** [HerbertHe/iptv-sources#55]
**描述问题 Describe the bug**

**如何复现 To Reproduce**
Steps to reproduce the behavior.

**期待结果 Expected behavior**

**截图 Screenshots**

**其他补充 Additional context**

**Comment by mbyd2022** [comment]
部署到docker后，打开网页显示下面这样是什么原因啊？
![捕获](https://github.com/HerbertHe/iptv-sources/assets/106051448/809a8970-32d1-4c2d-8ddd-27b4d4164e50)
