### ISSUE TITLE
dockercompose启动

### ISSUE THREAD

**Issue by mizb** [HerbertHe/iptv-sources#6]
我按信息，自己编写了一份dockercompose。但是启动报错。

报错信息如下：
yarn run v1.22.19
$ npx live-server ./m3u --port 8080
Need to install the following packages:
iptv  | live-server@1.2.2

dockercompose信息如下：
version: "3.8"

networks:
  lan:
    name: lan
    external: true
    
services:
 iptv:
    image: herberthe0229/iptv-sources:latest
    container_name: iptv
    hostname: iptv
    restart: always
    tty: true
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=000
      - TZ=Asia/Shanghai

    network_mode: "lan"
    networks:
      lan:
        ipv4_address: "192.168.31.224"
    dns:
      - 223.5.5.5
      - 119.29.29.29

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

**Comment by HerbertHe** [comment]
没有计划支持 docker compose，看报错信息的话是不支持 npx 直接启用 live-server 这个包。可能是你环境的问题，建议用 docker 直接启动。

**Comment by HerbertHe** [comment]
Docker run 的日志是：

```text
npm WARN exec The following package was not found and will be installed: live-server@1.2.2
```

会自动下载这个包

**Comment by mizb** [comment]
qnap环境，使用docker部署，一样的报错信息。

**Comment by HerbertHe** [comment]
@mizb

**Comment by mizb** [comment]
使用新版镜像，可完美启动。可以适配dockercompose

**Comment by HerbertHe** [comment]
@mizb 这个应该就是 live-server 导致的，我重写了静态服务
