### ISSUE TITLE
[✨Feat] 可以直接在crontab 里面写配置

### ISSUE THREAD

**Issue by wxkeykey** [HerbertHe/iptv-sources#61]
# 打开crontab配置文件
crontab -e

# 添加以下行到crontab文件中
0 */2 * * * docker exec -d iptv-sources /bin/sh ./update-sources.sh >/dev/null 2>&1

这样就每2个小时自动执行一次了

**Comment by HerbertHe** [comment]
没区别是一样的，我考虑的是直接放掉脚本文件，直接通过 env.json 的 config 文件进行更新和重启这些逻辑，这样就不用带环境变量了
