### ISSUE TITLE
[🐛BUG]Docker跑出来的IPV6电视源不是最优的

### ISSUE THREAD

**Issue by skyblue0511** [HerbertHe/iptv-sources#62]
**描述问题 Describe the bug**
比如央视的CCTV4,显示500多毫秒延迟。如果引用Meroser的源，速度会好很多。
![20240224_222012](https://github.com/HerbertHe/iptv-sources/assets/47215435/6522b994-e24c-414b-b43e-fba44eb7c195)
![17087844926421434536210853660333](https://github.com/HerbertHe/iptv-sources/assets/47215435/ede8df37-7cb8-4114-ac4f-2dac7626ac14)

**如何复现 To Reproduce**
Steps to reproduce the behavior.

**期待结果 Expected behavior**

**截图 Screenshots**

**其他补充 Additional context**

**Comment by HerbertHe** [comment]
不太懂你是啥意思？

**Comment by skyblue0511** [comment]
就是Docker生成的cn.m3u里面电视台延迟都比较高。

**Comment by HerbertHe** [comment]
来源不一样啊
