### ISSUE TITLE
部署后容器自动停止

### ISSUE THREAD

**Issue by HelloMusician** [HerbertHe/iptv-sources#7]
![3a1e48526aeaec5e51700b8e1aff5adb](https://github.com/HerbertHe/iptv-sources/assets/105097307/aa7c7dbb-bc10-4a6a-b51d-b7e563ec9eb4)
如图，docker容器部署成功，但是启动的时候会自动停止，有报错

**Comment by HerbertHe** [comment]
请给一下完整的日志

**Comment by HerbertHe** [comment]
最新的镜像移除了 live-server 支持更好的性能，应该可以解决目前的问题，已经移除了 live-server 的依赖了

**Comment by HerbertHe** [comment]
升级到最新的镜像，这个问题应该已经解决了

**Comment by HelloMusician** [comment]
是的，我今天重新部署的就可以用了，谢谢大佬

Herbert He ***@***.***> 于2023年12月18日周一 20:49写道：
