### ISSUE TITLE
关于直播源中北京IPTV直播源建议[✨Feat]

### ISSUE THREAD

**Issue by chinesepy** [HerbertHe/iptv-sources#75]
**描述是否与问题相关 Is your feature request related to a problem? Please describe.**
直播源中几条涉及qwerttvv/Beijing-IPTV 的单播直播源默认地址为'http://192.168.123.1:23234/rtp/组播地址'，如果网段不是123网段则无法直接使用

**描述你倾向的解决方案 Describe the solution you'd like**
修改update-sources.sh，加入查找并替换指定文件中的IP功能。比如
`sed -i "s/$OLD_IP/$NEW_IP/g" "$DESTINATION"` 这样的
或者把直播源挂载出来，在计划任务里头改

**描述你考虑过的其他方案 Describe alternatives you've considered**
PS：部分文件名太长了，电视上输起来有点费劲，改短一点可能会更好。

**Comment by HerbertHe** [comment]
网段地址这个问题，可以后面考虑通过自定义替换函数的方式进行实现。不太认同你的这个方案，因为不具备通用性，通过修改脚本的方式可以自己进行特殊实现。

文件名的问题，不再考虑缩短了，因为已经是缩短之后的了，电视上操作还是建议用手机输入法进行连接输入吧。

**Comment by HerbertHe** [comment]
最新的版本已经支持通过 `custom.json` 配置 `replacer.url` 字段来实现你的替换网段的需求
