### ISSUE TITLE
自定义custom.json，url无法自动更新，始终为custom.json配置的地址

### ISSUE THREAD

**Issue by 897896639** [HerbertHe/iptv-sources#77]
[custom.json](https://github.com/HerbertHe/iptv-sources/files/14716272/custom.json)
附件为custom.json内容，不知道哪里出现的问题，
![image](https://github.com/HerbertHe/iptv-sources/assets/3367042/87532ce0-073f-475a-bc75-31b2995ffe13)
执行sh update-sources.sh后，新生成custom文件夹下txt文件为
![image](https://github.com/HerbertHe/iptv-sources/assets/3367042/66cedd9c-4e3b-40e0-a309-248eeea7b530)
url无法自动更新为最新的直播源地址。

**Comment by HerbertHe** [comment]
@897896639 你的文件写的有问题，我的实例里面是列举了所有的可配置项。当 include 存在时，遵循白名单机制，文档里面已经写清楚了。append 是你自己增加的地址，当然无法更新
