### ISSUE TITLE
[🐛BUG]最近电视端DIYP突然收不到订阅了

### ISSUE THREAD

**Issue by xiaoxinpro** [HerbertHe/iptv-sources#83]
**描述问题 Describe the bug**
电视端DIYP突然收不到订阅了

**如何复现 To Reproduce**
电视端安装DIYP或百川影音，在订阅中填写`https://m3u.ibert.me/txt/fmml_ipv6.txt`，重启软件

**期待结果 Expected behavior**
年前的时候还可以收到订阅源，现在访问不到了

**截图 Screenshots**
NULL

**其他补充 Additional context**
[百川影音1.1.7.zip](https://github.com/HerbertHe/iptv-sources/files/14918836/1.1.7.zip)
[DIYP_Final.zip](https://github.com/HerbertHe/iptv-sources/files/14918843/DIYP_Final.zip)

**Comment by HerbertHe** [comment]
你换个源试试，我看了一下fmm的上游换掉了

**Comment by xiaoxinpro** [comment]
并不是iptv源得问题，因为我手动将txt文件内容添加到APP中是可以正常播放得，问题是APP无法获取`https://m3u.ibert.me/txt/fmml_ipv6.txt` 链接的内容。

**Comment by HerbertHe** [comment]
@xiaoxinpro 那很有可能是你当地的运营商把我的域名屏蔽了，要不就是阻断了 GitHub 的 ip

**Comment by HerbertHe** [comment]
@xiaoxinpro 在本地的网络环境，打开浏览器按 f12 选到网络，然后访问一下这个链接，之后截个图给我看一下就知道原因了

**Comment by xiaoxinpro** [comment]
> @xiaoxinpro 那很有可能是你当地的运营商把我的域名屏蔽了，要不就是阻断了 GitHub 的 ip

应该不是这个问题，因为我本地docker搭建的iptv-sources也是一样的现象

**Comment by xiaoxinpro** [comment]
> @xiaoxinpro 在本地的网络环境，打开浏览器按 f12 选到网络，然后访问一下这个链接，之后截个图给我看一下就知道原因了

浏览器访问不存在问题，我晚些时候尝试把txt重新部署一个web服务试试看。

**Comment by HerbertHe** [comment]
@xiaoxinpro 如果复制内容可以播放的话，就不是bug了，可能就是客户端存在问题

<img width="621" alt="image" src="https://github.com/HerbertHe/iptv-sources/assets/30955264/7d53ff78-d132-4ed7-816a-97a79625d4be">

**Comment by HerbertHe** [comment]
那唯一的问题，就可能是上面那个h字符导致的

**Comment by xiaoxinpro** [comment]
@HerbertHe 也许就是APP的问题，有什么电视端的APP推荐吗？

**Comment by HerbertHe** [comment]
@xiaoxinpro 如果是复制可以用的话，这我不太能理解原因。电视端的话，我自己用的 kodi，看了一下 GitHub 的 my-tv 好像也可以用，其实替换一下他的 channels.json 就好了，本身没啥困难
