### ISSUE TITLE
docker部署后更新custom.json，无法完全执行custom规则，以及在原映射目录内生成custom.m3u或类似文件

### ISSUE THREAD

**Issue by newrookie001** [HerbertHe/iptv-sources#87]
docker部署了iptv-sources，
[custom (2).json](https://github.com/HerbertHe/iptv-sources/files/15218827/custom.2.json)
目前碰到问题有两个：
1、执行custom.json后，exclude下的央视频道无法剔除，但剔除卫视频道、数字频道规则是可以的，不知道是否是我央视频道规则/文本写错了；
2、执行前述更新后，本地会生成一个xxx.m3u文件，但这个文件无法通过文件夹映射保存（或直接生成在）指定文件夹内

**Comment by HerbertHe** [comment]
问题一：一定是你写错了
问题二：不允许指定，默认在 `/custom`
