### ISSUE TITLE
[🐛BUG] 不知道怎么创建容器

### ISSUE THREAD

**Issue by bike3097a** [HerbertHe/iptv-sources#93]
docker run命令是啥，告诉我下，麻烦大家了。目前就docker pull好了。

**Comment by yingkong1987** [comment]
docker run --name iptv-sources -p 3000:8080 -d herberthe0229/iptv-sources:latest

这里有写： [https://github.com/HerbertHe/iptv-sources/discussions/36](url)
> docker run命令是啥，告诉我下，麻烦大家了。目前就docker pull好了。

**Comment by bike3097a** [comment]
已经解决
