### ISSUE TITLE
[🐛BUG] EPG获取失败

### ISSUE THREAD

**Issue by kimwu2009** [HerbertHe/iptv-sources#95]
**描述问题 Describe the bug**

112114 EPG 一直显示 update failed
```
TypeError: fetch failed
    at node:internal/deps/undici/undici:13737:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async W (file:///app/dist/index.js:9:328)
    at async file:///app/dist/index.js:22:1240
    at async Promise.allSettled (index 0)
    at async file:///app/dist/index.js:22:1142 {
  [cause]: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
```
加 log 显示以上异常，对网络接口不太熟悉，不知道啥问题

**截图 Screenshots**

![x](https://github.com/user-attachments/assets/ec3bd696-7bba-48e6-83db-2f77b66009c2)

**其他补充 Additional context**

另：浏览代码的时候发现 rollback 有个链接写错了
https://github.com/HerbertHe/iptv-sources/blob/ba2044403c136ba69b3e80e497f258d971e3081b/src/rollback.ts#L59
这里应该是 `${rollback_urls[idx]}/epg/${sr.f_name}.xml`，修改后回滚正常。

**Comment by HerbertHe** [comment]
@kimwu2009 有时间来解决这个，周末吧

**Comment by HerbertHe** [comment]
update failed 可能是被限制了吧

**Comment by Doctorlee0827** [comment]
出现一样的问题一周了，以为是自己docker网络配置问题，希望修复~

**Comment by shit6** [comment]
一个能看的都没有了
